package example.carsharingprototype;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Places in the car")
   private java.lang.Integer places;
   @org.kie.api.definition.type.Label("Licence plate")
   private java.lang.String licencePlate;
   @org.kie.api.definition.type.Label("Color")
   private java.lang.String color;
   @org.kie.api.definition.type.Label("Photo")
   private java.lang.String photo;
   @org.kie.api.definition.type.Label("Model")
   private java.lang.String model;

   @org.kie.api.definition.type.Label(value = "Is verified")
   private java.lang.Boolean isVerified;

   public Car()
   {
   }

   public java.lang.Integer getPlaces()
   {
      return this.places;
   }

   public void setPlaces(java.lang.Integer places)
   {
      this.places = places;
   }

   public java.lang.String getLicencePlate()
   {
      return this.licencePlate;
   }

   public void setLicencePlate(java.lang.String licencePlate)
   {
      this.licencePlate = licencePlate;
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public java.lang.String getPhoto()
   {
      return this.photo;
   }

   public void setPhoto(java.lang.String photo)
   {
      this.photo = photo;
   }

   public java.lang.String getModel()
   {
      return this.model;
   }

   public void setModel(java.lang.String model)
   {
      this.model = model;
   }

   public java.lang.Boolean isIsVerified()
   {
      return this.isVerified;
   }

   public void setIsVerified(java.lang.Boolean isVerified)
   {
      this.isVerified = isVerified;
   }

   public Car(java.lang.Integer places, java.lang.String licencePlate,
         java.lang.String color, java.lang.String photo, java.lang.String model,
         java.lang.Boolean isVerified)
   {
      this.places = places;
      this.licencePlate = licencePlate;
      this.color = color;
      this.photo = photo;
      this.model = model;
      this.isVerified = isVerified;
   }

}