package example.carsharingprototype;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PaymentCard implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PAYMENTCARD_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PAYMENTCARD_ID_SEQ", name = "PAYMENTCARD_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Card number")
   private java.lang.String cardNumber;

   @org.kie.api.definition.type.Label(value = "Expiration date")
   private java.util.Date expirationDate;

   @org.kie.api.definition.type.Label(value = "Security code")
   private java.lang.String securityCode;

   public PaymentCard()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCardNumber()
   {
      return this.cardNumber;
   }

   public void setCardNumber(java.lang.String cardNumber)
   {
      this.cardNumber = cardNumber;
   }

   public java.util.Date getExpirationDate()
   {
      return this.expirationDate;
   }

   public void setExpirationDate(java.util.Date expirationDate)
   {
      this.expirationDate = expirationDate;
   }

   public java.lang.String getSecurityCode()
   {
      return this.securityCode;
   }

   public void setSecurityCode(java.lang.String securityCode)
   {
      this.securityCode = securityCode;
   }

   public PaymentCard(java.lang.Long id, java.lang.String cardNumber,
         java.util.Date expirationDate, java.lang.String securityCode)
   {
      this.id = id;
      this.cardNumber = cardNumber;
      this.expirationDate = expirationDate;
      this.securityCode = securityCode;
   }

}